### ISSUE TITLE
So much potential extension!

### ISSUE THREAD

**Issue by WilliamLeGod** [Lacro59/playnite-backgroundchanger-plugin#14]
I would like to add more details so that you can perfect this potential extension!:

1/ Make it work in fullscreen mode
2/ Provide a guide to add the plugin into any theme for example Ps5ish fullscreen theme

Thanks!

**Comment by Lacro59** [comment]
The plugin works in fullscreen mode.

Here an example with PS5ish:
[Main.zip](https://github.com/Lacro59/playnite-backgroundchanger-plugin/files/7769562/Main.zip)

**Comment by WilliamLeGod** [comment]
> The plugin works in fullscreen mode.
> 
> Here an example with PS5ish: [Main.zip](https://github.com/Lacro59/playnite-backgroundchanger-plugin/files/7769562/Main.zip)

Omg thank you so much! It works!!!
To be honest I really want to make it like this: Show background image for like 5 seconds and automatcially change to a video background but this video will run for eternity until I change game icon. Is this possible?
