### ISSUE TITLE
Backgrounds do not display

### ISSUE THREAD

**Issue by bentout12** [Lacro59/playnite-backgroundchanger-plugin#20]
Plugin seems to have no effect when enabled. No matter what options are selected, the background for a game does not change from the default image provided within Playnite settings. This problem is the same for cover images, as well. Occurs with the latest Playnite v 9.14 version and the latest 2.1 version of this plugin.

**Comment by Lacro59** [comment]
Do you used a compatible theme?

**Comment by Lacro59** [comment]
Any news?
