### ISSUE TITLE
Failed to load setting

### ISSUE THREAD

**Issue by zam-fir** [Lacro59/playnite-backgroundchanger-plugin#28]
It seem that the extension cannot load the setting at the menu but you can still add the background and stuff.. and also it seem it cannot get anything from the SteamGridDb also... Thanks for your hard work though! Appreciate it a lot!

**Comment by cnapolit** [comment]
Experiencing the same exact issue. Here's what's in the log:
04-10 10:02:31.043|ERROR|ExtensionFactory:Failed to load plugin: BackgroundChanger
04-10 10:02:31.043|ERROR|ExtensionFactory:
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)

**Comment by bentout12** [comment]
Running into the same issue, as well. Switching themes, updating PlayNite, reinstalling the add-on or the program don't seem to help.

**Comment by Exergist** [comment]
Same

![image](https://user-images.githubusercontent.com/31357974/203234464-a9a7ab50-8d8b-4cc0-afc5-e3318415c3d5.png)

**Comment by DeFishe** [comment]
I'm having the same issues. No settings and no SteamGridDB.

**Comment by Tomax55** [comment]
why do not fix this problem ?? 😢😢

**Comment by Jambopaul** [comment]
How do I install the commits? Whenever I try to install the plugin through the Playnite Add-On/Extension browser, it seems to just install the latest release version without any commits.
