### ISSUE TITLE
Library is not updating with extension turned on

### ISSUE THREAD

**Issue by Landxhent** [Lacro59/playnite-backgroundchanger-plugin#3]
It seems like the extension (ver. 1.1) cause the playnite library update to fail. The error looks like

**ERROR|DesktopAppViewModel:Failed to import games from plugin: Ubisoft Connect
System.InvalidOperationException: Вызывающий поток не может получить доступ к данному объекту, так как владельцем этого объекта является другой поток.** sorry for russian.

After checking the playnite.log file, i've found following text next to each (steam, battle.net, origin, etc.) library row:

15-02 11:26:08.635|INFO|DesktopAppViewModel:Importing games from Ubisoft Connect plugin.
15-02 11:26:08.635|DEBUG|UplayLibrary:Found 1 installed Uplay games.
15-02 11:26:09.205|DEBUG|UplayLibrary:Found 17 library Uplay games.
15-02 11:26:09.207|ERROR|DesktopAppViewModel:Failed to import games from plugin: Ubisoft Connect
System.InvalidOperationException: Вызывающий поток не может получить доступ к данному объекту, так как владельцем этого объекта является другой поток.
   **в System.Windows.Threading.Dispatcher.VerifyAccess()
   в BackgroundChanger.BackgroundChanger.SetImage() в H:\GitHub\Lacro59\playnite-backgroundchanger-plugin\BackgroundChanger.cs:строка 211
   в BackgroundChanger.BackgroundChanger.Games_ItemUpdated(Object sender, ItemUpdatedEventArgs`1 e) в H:\GitHub\Lacro59\playnite-backgroundchanger-plugin\BackgroundChanger.cs:строка 70**
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в Playnite.Database.ItemCollection`1.OnItemUpdated(IEnumerable`1 updates) в E:\Devel\Playnite\source\Playnite\Database\Collections\ItemCollection.cs:строка 504
   в Playnite.Database.ItemCollection`1.Update(TItem itemToUpdate) в E:\Devel\Playnite\source\Playnite\Database\Collections\ItemCollection.cs:строка 397
   в Playnite.Database.GamesCollection.Update(Game itemToUpdate) в E:\Devel\Playnite\source\Playnite\Database\Collections\GamesCollection.cs:строка 131
   в Playnite.Database.GameDatabase.ImportGames(LibraryPlugin library, Boolean forcePlayTimeSync, IList`1 excludedItems) в E:\Devel\Playnite\source\Playnite\Database\GameDatabase.cs:строка 1086
   в Playnite.DesktopApp.ViewModels.DesktopAppViewModel.<>c__DisplayClass390_0.<UpdateDatabase>b__0() в E:\Devel\Playnite\source\Playnite.DesktopApp\ViewModels\DesktopAppViewModel.cs:строка 1178

After i've disabled the extension, library is updating again as it should.

Attaching whole playnite.log below

Maybe this will help to find the true causes, because, in the end, it maybe not the extension issue, but mine, somehow.
[playnite.log](https://github.com/Lacro59/playnite-backgroundchanger-plugin/files/5997130/playnite.log)

**Comment by Landxhent** [comment]
Translator given something like this **The caller cannot access the object because the object is owned by another thread**

**Comment by Lacro59** [comment]
Are you still having the problem with the latest version?
