### ISSUE TITLE
Window background settings also affect game background when plugin is turned on

### ISSUE THREAD

**Issue by vulpesfelix** [Lacro59/playnite-backgroundchanger-plugin#37]
As noted [here](https://github.com/darklinkpower/Harmony/issues/25#issue-1952614857).

**Comment by Itzhak880** [comment]
I'm also having this issue.
I've described it [here](https://github.com/darklinkpower/PlayniteExtensionsCollection/issues/462). 
Note that at the time of writing it I thought the problem was within the theme, but now it clear that "BackgroundChanger" is what's causing this.

**Comment by Itzhak880** [comment]
Yo that's crazy I found a fix to this problem.
Download "ThemeModifier" extension and enable "Use low performance blurred game background image".
I still hope it gets fixed on the extension's side.
